/*===================================-	Purpose : Customer Revenue Summary -===================================*/

--Create a view that shows every customer and the total revenue generated by that customer.
CREATE VIEW View_Customer_revenue as 
(
	SELECT 
		c.Customer_Name,
		c.Customer_Id,
	ISNULL(SUM(o.Total_Amount),0) as Total_customer_revenue
	FROM dbo.Customers as c
	LEFT JOIN dbo.Orders as o
	ON c.Customer_Id=o.Customer_Id
	GROUP BY 
		c.Customer_Name,
		c.Customer_Id
)

--check

SELECT *
FROM dbo.View_Customer_revenue;
