/*===============-	Purpose : Create a reusable view showing store-level sales performance. -===============*/
--Show every store, the number of orders handled by that store, and the total revenue generated by that store


CREATE VIEW View_Store_performance as 
(

	SELECT 
		s.Store_Id,
		s.Store_Name,
		ISNULL(count(o.order_id),0) as Order_count,
		ISNULL(SUM(o.total_amount),0) as total_revenue
	FROM dbo.Stores as s
	LEFT JOIN dbo.Employees as e
	ON s.Store_Id=e.Store_Id
	LEFT JOIN dbo.Orders as o
	ON e.Employee_Id=o.Employee_Id
	GROUP BY 
		s.Store_Id,
		s.Store_Name
)