/*===============-	Purpose : Create a reusable view showing category-level sales performance. -===============*/
--Show every product category, the total quantity sold from that category, and the total revenue generated by that category.


CREATE VIEW View_Categories_Performance as 
(

	SELECT 
		c.Category_Id,
		c.Category_Name,
		ISNULL(SUM(oi.Quantity),0) as Total_Quantity,
		ISNULL(SUM(oi.Unit_Price*oi.Quantity),0) as Total_revennue
	FROM dbo.Categories as c
	LEFT JOIN dbo.products as p
	ON c.Category_Id=p.Category_Id
	LEFT JOIN dbo.OrderItems as oi
	ON p.Product_Id=oi.Product_Id
	GROUP BY 
		c.Category_Id,
		c.Category_Name

)